# Generated by Django 5.0.6 on 2024-07-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubtaskModel',
        ),
    ]
