# Generated by Django 5.0.6 on 2024-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_taskmodel_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='SubtaskModel',
        ),
    ]
