# Generated by Django 5.0.6 on 2024-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_taskmodel_subtasks_delete_subtaskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
