# Generated by Django 5.0.6 on 2024-07-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
