# Generated by Django 5.0.6 on 2024-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='initials',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
