# Generated by Django 5.0.6 on 2024-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_contact_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
