# Generated by Django 5.0.6 on 2024-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_contact_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='taskapp.contact'),
        ),
    ]
